#!/bin/bash

ALLNODES=()
for n; do
    newnodes=( $( nodels $n 2>/dev/null ) )
    if [[ $? -gt 0 ]] ; then
        echo "Skipping invalid noderange '$n'"
        continue
    fi
    for nn in ${newnodes[@]}; do
        ALLNODES[${#ALLNODES[*]}]=$nn
    done
done

for n in "${ALLNODES[@]}"; do
    mac=$( rinv "$n" mac | awk '/: MAC Address 1:/ {print $NF}' )
    if [[ ${#mac} -ne 17 ]]; then
        echo "Skipping invlid mac '$mac' for node '$n'"
        continue
    fi
    set -x
    nodech "$n" mac.mac="$mac"
    set +x
done
