show DevicesandIOPorts.UEFI_Slot1
show DevicesandIOPorts.UEFI_Slot3
show DevicesandIOPorts.UEFI_Slot4
show DevicesandIOPorts.UEFI_Slot5
show DevicesandIOPorts.UEFI_Slot6
show DevicesandIOPorts.UEFI_Slot7
show DevicesandIOPorts.UEFI_Slot8
show DevicesandIOPorts.Legacy_Slot1
show DevicesandIOPorts.Legacy_Slot3
show DevicesandIOPorts.Legacy_Slot4
show DevicesandIOPorts.Legacy_Slot5
show DevicesandIOPorts.Legacy_Slot6
show DevicesandIOPorts.Legacy_Slot7
show DevicesandIOPorts.Legacy_Slot8
 
show DevicesandIOPorts.UEFI_Ethernet1
show DevicesandIOPorts.UEFI_Ethernet2
show DevicesandIOPorts.UEFI_Ethernet3
show DevicesandIOPorts.UEFI_Ethernet4
show DevicesandIOPorts.Legacy_Ethernet1
show DevicesandIOPorts.Legacy_Ethernet2
show DevicesandIOPorts.Legacy_Ethernet3
show DevicesandIOPorts.Legacy_Ethernet4
 
show Processors.Hyper_Threading
show OperatingModes.ChooseOperatingMode
 
show Power.PlatformControlledType
show Power.ZeroOutput
show Processors.C1EnhancedMode
 
show Processors.C-States
show Processors.CPUP_stateControl
show Processors.PerCoreP-state
show Memory.SocketInterleave
show Memory.MemoryDataScrambling
show BootModes.SystemBootMode
 
show PXE.NicPortPxeMode.1
 
show DevicesandIOPorts.COMPort1
show DevicesandIOPorts.RemoteConsole
show DevicesandIOPorts.SerialPortSharing
show DevicesandIOPorts.SerialPortAccessMode
show DevicesandIOPorts.LegacyOptionROMDisplay
show DevicesandIOPorts.Com1BaudRate
show DevicesandIOPorts.Com1DataBits
show DevicesandIOPorts.Com1Parity
show DevicesandIOPorts.Com1StopBits
