#!/bin/bash

###
# Description: Custom postscript for xcat.
#              Re-install kerberos keytab (if preciously backed up)
# Source: https://github.com/ncsa/xcat-tools
###

#
# PREP
#
PRG=$( basename $0 )
logger -t xcat -p local4.info "running '$PRG' on node $NODE"


#
# DEFAULT SETTINGS
#
KEYTABDIR=/etc
BKUP_KEYTABDIR=/install/files/compute/var/lib/kerberos/keytab


#
# FUNCTIONS
#
logr() {
  logger -t xcat -p local4.info "$*"
  echo "$*"
}


croak() {
  logr "ERROR - $*"
  echo "ERROR - $*"
  exit 99
}


#
# DO WORK
#
logr "ensure $MASTER:$INSTALLDIR is mounted"
/xcatpost/mountinstall || exit 2
logr "ensure $MASTER:$INSTALLDIR is mounted ... OK"
#ls -R /install

logr "copying kerberos keytab from the master."
set -x
srcfn="$BKUP_KEYTABDIR/${NODE}.krb5.keytab"
tgtfn="$KEYTABDIR/krb5.keytab"
if [[ -f "$srcfn" ]]; then
  logr "found keytab file '$srcfn'"
  cp "$srcfn" "$tgtfn"
  chmod 600 "$tgtfn"
  chown root.root "$tgtfn"
fi

if [[ -f "$tgtfn" ]] ; then
    logr "Successfully installed keytab '$tgtfn'"
else
    logr "Keytab file not installed"
fi
ls -R $KEYTABDIR/krb5.keytab
strings $KEYTABDIR/krb5.keytab | grep -i '${NODE}'
set +x
logr "copying kerberos keytab from the master ... OK"


logr "end of kerberos_keytab on OS '$OSVER' on node '$NODE'"

exit 0
