#!/bin/bash

###
# Description: Configure Puppet agent
# 1. Install puppet-agent
#     1. Check if puppet agent is present: yes = stop
#     2. Check if puppet repo is configured: yes = install puppet-agent
#     3. Check if puppet repo available in /install/postscripts/repos
#     4. Check if puppet-agent rpm is available in /install/postscripts/custom/rpms
# 2. Configure puppet server in puppet config file, if not already set
# 3. Configure puppet certname in puppet config file, if not already set
#
# Note: Puppet agent service is started/enabled via puppet_run.
#       Some use cases require puppet run to happen at a later time.
#
# Note: This script depends on
#       - backup-node_configs
#         + to backup puppet config file and puppet ssl dir
#       - restore-node_configs
#         + to restore those things above
#
# Note: If config file already contains server or certname, those settings are not
#       added or updated.
#
# Usage:
#      1. use $PUPPETMASTER as the puppet server (for new nodes only)
#         updatenode <noderange> -P "custom/puppet_configure"
#
# Source: https://github.com/ncsa/xcat-tools
###


# PREP
PRG=$( basename $0 )
logger -t xcat -p local4.info "running '$PRG' on node $NODE"


# DEFAULT SETTINGS
PUPPET=/opt/puppetlabs/bin/puppet
REPO_BASEURL=   #explicitly set repo baseurl
REPO_DIR_SEARCH_LOCATIONS=( /xcatpost/repos/puppet )
RPM_SEARCH_LOCATIONS=( /xcatpost/custom/rpms )
PUPPETSERVER=$PUPPETMASTER
PUPPETSERVERIP=""


# FUNCTIONS
logr() {
  logger -t xcat -p local4.info "$*"
  echo "$*"
}


croak() {
  logr "ERROR - $*"
  echo "ERROR - $*"
  exit 99
}


set_hosts_entry() {
    logr "enter '$FUNCNAME'..."
    HOSTSFILE="/etc/hosts"
    HOSTENTRY="$PUPPETSERVERIP $PUPPETSERVER"
    logr "clearing $PUPPETSERVERIP from $HOSTSFILE"
    grep -v "$PUPPETSERVERIP" $HOSTSFILE >> $HOSTSFILE
    logr "adding '$HOSTENTRY' to $HOSTSFILE"
    echo "$HOSTENTRY" >> $HOSTSFILE
    logr "... exit '$FUNCNAME'"
}


set_server() {
    logr "enter '$FUNCNAME'..."
    if ! grep -qw server /etc/puppetlabs/puppet/puppet.conf ; then
        logr "setting server setting to '$PUPPETSERVER' in local config"
        $PUPPET config set server "$PUPPETSERVER" --section agent
        logr "verify server setting is saved in local config"
        $PUPPET config print server --section agent
    else
        logr "found existing server in config file, not setting server"
    fi
    logr "... exit '$FUNCNAME'"
}


set_certname() {
    logr "enter '$FUNCNAME'..."
    if ! grep -qw certname /etc/puppetlabs/puppet/puppet.conf ; then
        if [ ! -z $DOMAIN ]; then
            SET_CERTNAME=$NODE.$DOMAIN
        else
            SET_CERTNAME=$NODE.local
        fi
        logr "setting certname setting to '$SET_CERTNAME' in local config"
        $PUPPET config set certname "$SET_CERTNAME" --section agent
        logr "verify certname setting is saved in local config"
        $PUPPET config print certname --section agent
    else
        logr "found existing certname in config file, not setting certname"
    fi
    logr "... exit '$FUNCNAME'"
}


is_agent_installed() {
    logr "is agent installed"
    [[ -f "$PUPPET" ]]
    local _rc=$?
    [[ $_rc -eq 0 ]] && logr '...yes' || logr '...NO'
    return $_rc
}


is_repo_installed() {
    logr "is repo installed"
    yum repolist | grep 'Puppet \(\w \)\?Repo'
    local _rc=$?
    [[ $_rc -eq 0 ]] && logr '...yes' || logr '...NO'
    return $_rc
}


install_repo() {
    local _rc=1
    local _baseurl="$REPO_BASEURL"
    if [[ -z "$_baseurl" ]] ; then
        # REPO_BASEURL was empty, so try scanning repo dir locations
        for repodir in "${REPO_DIR_SEARCH_LOCATIONS[@]}"; do
            if [[ -f "$repodir"/repodata/repomd.xml ]]; then
                _baseurl="file://$repodir"
                break
            fi
        done
    fi
    if [[ -n "$_baseurl" ]] ; then
        logr "installing puppet repo with baseurl: '$_baseurl'"
        repofile=/etc/yum.repos.d/puppet.repo
        >$repofile echo "[puppet]"
        >>$repofile echo "name=Puppet Repository"
        >>$repofile echo "baseurl=$_baseurl"
        >>$repofile echo "enabled=1"
        >>$repofile echo "gpgcheck=0"
        _rc=0
    fi
    return $_rc
}


install_from_repo() {
    logr "attempting install puppet agent from repo"
    is_repo_installed || install_repo 
    is_repo_installed && yum -y install puppet-agent
}


install_rpm() {
    logr "looking for a puppet-agent rpm to install"
    local _rc=1
    for dir in "${RPM_SEARCH_LOCATIONS[@]}"; do
        rpm=$( find "$dir" -name 'puppet-agent*rpm' -print | sort -V | tail -1 )
        logr "installing puppet-agent rpm from: '$rpm'"
        yum install -y "$rpm"
        _rc=$?
        break
    done
    return $_rc
}


print_usage() {
    cat <<ENDHERE
Usage:
    puppet_configure [OPTIONS]

OPTIONS:
    -h | --help
        Print usage message and exit
    --host <HOSTNAME>
        Set Puppet server to HOSTNAME
    --ip <IPADDRESS>
        Create local hosts entry for IPADDRESS to point to puppet server hostname

ENDHERE
}


# DO WORK
ENDWHILE=0
while [[ $# -gt 0 ]] && [[ $ENDWHILE -eq 0 ]] ; do
  case $1 in
    -h|--help)
        print_usage
        exit 0
        ;;
    --host)
        PUPPETSERVER="$2"
        shift
        ;;
    --ip)
        PUPPETSERVERIP="$2"
        shift
        ;;
    --)
        ENDWHILE=1
        ;;
    -*)
        croak "Invalid option '$1'"
        ;;
     *)
        ENDWHILE=1
        break
        ;;
  esac
  shift
done

is_agent_installed || install_from_repo
is_agent_installed || install_rpm
is_agent_installed || croak "Failed to install puppet-agent"

set_server
set_certname

[[ -n "$PUPPETSERVERIP" ]] && set_hosts_entry

logr "end of puppet_configure on OS '$OSVER' on node '$NODE'"

exit 0

